### ISSUE TITLE
greaterThan modifying values, even when cloned

### ISSUE THREAD

**Issue by gxavier38** [dennis-jiang/fraction-calculator#3]
Hi,

I have a question about the behaviour of `greaterThan()`. If I run something like:
```
a = fc(10);
b = fc(5);
b.greaterThan(a);
```
I get some unexpected behaviour:
```
a.toFraction(); // Prints "-10"
b.toFraction(); // Prints "-5"
```

I thought I could try cloning beforehand but I get similar results:
```
b.clone().greaterThan(a.clone());
a.toFraction() // Prints "-10"
b.toFraction() // Prints "5"
```

Any ideas why?

**Comment by dennis-jiang** [comment]
@gxavier38 I fixed it, please try 1.0.14
